apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-service
  labels:
    {{- include "job-scraper-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}
    protocol: TCP
    name: http
  selector:
    {{- include "job-scraper-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
