apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "job-scraper-app.fullname" . }}-config
  labels:
    {{- include "job-scraper-app.labels" . | nindent 4 }}
data:
  DATABASE_URL: "postgresql://admin:$(POSTGRES_PASSWORD)@{{ .Values.postgres.name }}-service:{{ .Values.postgres.service.port }}/jobscraper"
  REDIS_URL: "redis://{{ .Values.redis.name }}-service:{{ .Values.redis.service.port }}"
  REDIS_HOST: "{{ .Values.redis.name }}-service"
  REDIS_PORT: "{{ .Values.redis.service.port }}"
  DATA_DIR: "/app/data"
