{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}-service
  labels:
    {{- include "job-scraper-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: {{ .Values.postgres.service.type }}
  clusterIP: None
  ports:
  - port: {{ .Values.postgres.service.port }}
    targetPort: {{ .Values.postgres.service.port }}
    protocol: TCP
    name: postgres
  selector:
    {{- include "job-scraper-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
