apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    {{- include "job-scraper-app.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.secrets.postgres.password | b64enc | quote }}
