apiVersion: v2
name: job-scraper-app
description: A Helm chart for Job Scraper Application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - job-scraper
  - nestjs
  - svelte
maintainers:
  - name: Camille
